Change Pipfile to support pyjwt upgrade
18F/tock pull request #1491
Opened 2022-08-31 16:22 UTC by JeanMarie-TTS

## Description

pyjwt is used by cg-django-uaa. Due to s ecurity vulnerability in pyjwt 1,7, we need to upgrade these two packages.

## Additional information

* django test passed
* integration test failed, but it failed even before these changes (tested on an M1 laptop)
*

2022-08-31 18:00 UTC, neilmb commented
The Circle CI build is failing because the `Pipfile.lock` is not updated with the changes to the `Pipfile` https://app.circleci.com/pipelines/github/18F/tock/2025/workflows/c92f69bd-093e-49f9-8351-f7481079b665/jobs/7942?invite=true#step-103-29

> Your Pipfile.lock (e6e3a8) is out of date. Expected: (bbe7e5).

Can you run `pipenv lock` and commit the new `Pipfile.lock` as part of this PR?

2022-08-31 18:46 UTC, JeanMarie-TTS commented
Committed my local Pipfile.lock to the branch

On Wed, Aug 31, 2022 at 11:01 AM Neil MartinsenBurrell <
***@***.***> wrote:

> The Circle CI build is failing because the Pipfile.lock is not updated
> with the changes to the Pipfile
> https://app.circleci.com/pipelines/github/18F/tock/2025/workflows/c92f69bd-093e-49f9-8351-f7481079b665/jobs/7942?invite=true#step-103-29
>
> Your Pipfile.lock (e6e3a8) is out of date. Expected: (bbe7e5).
>
> Can you run pipenv lock and commit the new Pipfile.lock as part of this
> PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/tock/pull/1491#issuecomment-1233248978>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZYHCIPGULTFN7CGXTIQT5TV36MVNANCNFSM6AAAAAAQBREY4E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-07 16:14 UTC, cantsin commented
🤔 can we narrow down the `Pipfile.lock` changes to only these libraries that we are upgrading here (`pyjwt` and `cf-django-ua`)? We're pulling in a lot of other updates because of `*` and I think it's best to try and reduce the update churn here.

2022-09-07 19:25 UTC, JeanMarie-TTS commented
Need to discuss our approach to Pipfile. I did the following locally:
`pipenv --rm`
`git checkout main Pipfile`
`git checkout main Pipfile.lock`
`pipenv install --ignore-pipfile`
`pipenv install pyjwt~=2.4`
`pipenv install cg-django-uaa~=2.1.4`
Have not yet committed the changes. But there were other dependencies that got updated in Pipfile.lock as a result of the above commands. So, I'm not sure this is the way to proceed.

2022-09-08 17:50 UTC, cantsin approved these changes
LGTM!

2022-09-09 17:23 UTC, cantsin requested changes

2022-09-09 17:23 UTC, cantsin commented on doit.sh
> +docker-compose down
Do we want to add this file? Not sure where this came from.

2022-09-09 18:00 UTC, neilmb approved these changes

2022-09-09 18:05 UTC, cantsin approved these changes
LGTM

2022-09-09 20:34 UTC, merged